const socket = io();
const $ = id => document.getElementById(id);
const esc = s => String(s ?? "").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
const DEFAULT_AVATAR="https://i.imgur.com/6VBx3io.png";
let me=null,current=null,currentKind=null,selectedFile=null,recording=null,recordChunks=[],ownerPass="",roomComments=[],roomPerms=null;
let callPC=null,callStream=null,callType=null,callPeer=null,callMuted=false,callCamera=false,callIceQueue=[];
const livePeers=new Map(); let liveHost=false,liveStream=null,liveChatId=null,livePC=null;

function compressImage(file,cb,max=700){const r=new FileReader();r.onload=e=>{const i=new Image();i.onload=()=>{const c=document.createElement("canvas"),s=Math.min(1,max/Math.max(i.width,i.height));c.width=Math.max(1,Math.round(i.width*s));c.height=Math.max(1,Math.round(i.height*s));c.getContext("2d").drawImage(i,0,0,c.width,c.height);cb(c.toDataURL("image/jpeg",.78))};i.src=e.target.result};r.readAsDataURL(file)}
function fileToData(file,cb){const r=new FileReader();r.onload=e=>cb(e.target.result);r.readAsDataURL(file)}
function frameClass(id){return id?` frame-${String(id).replace(/^frame_/,'')}`:""}
function avatarHtml(user,size="normal"){const u=user||{};return `<span class="avatar-decor ${frameClass(u.frame)} ${u.badge?'has-badge':''}" style="--avatar-size:${size==='big'?110:size==='small'?44:48}px"><img src="${u.avatar||DEFAULT_AVATAR}">${u.badge?`<span class="avatar-badge">${badgeEmoji(u.badge)}</span>`:""}</span>`}
function setAppAvatar(src){$('myAvatar').src=src||DEFAULT_AVATAR;const wrap=$('myAvatar').parentElement;if(wrap)wrap.classList.toggle('has-frame',!!me?.frame);$('myNick').innerHTML=esc(me?.nickname||"")+(me?.badge?` <span class="pill">${badgeEmoji(me.badge)}</span>`:"");$('myUser').textContent=me?.username||""}

function showApp(){$("auth").classList.add("hidden");$("app").classList.remove("hidden");setAppAvatar(me.avatar)}
function refresh(){socket.emit("get_chats");socket.emit("get_balance")}
function closeModal(){$("modal").classList.add("hidden")}
window.closeModal=closeModal;

$("regFile").onchange=e=>{const f=e.target.files[0];if(f)compressImage(f,x=>$("regAvatar").src=x,500)};
$("loginBtn").onclick=()=>{const username=$("regUser").value.trim(),nickname=$("regNick").value.trim();if(!username||!nickname)return $("authError").textContent="Заповніть юзернейм та ім'я.";socket.emit("register",{username,nickname,avatar:$("regAvatar").src})};
$("regUser").onkeydown=e=>{if(e.key==="Enter")$("loginBtn").click()};$("regNick").onkeydown=e=>{if(e.key==="Enter")$("loginBtn").click()};
socket.on("register_success",u=>{me=u;localStorage.setItem("webchat_username",u.username);localStorage.setItem("webchat_nickname",u.nickname);localStorage.setItem("webchat_avatar",u.avatar||DEFAULT_AVATAR);showApp();refresh()});
socket.on("register_error",m=>$("authError").textContent=m);socket.on("error_msg",m=>alert(m));

socket.on("balance_update",x=>{if(!me)return;Object.assign(me,x);setAppAvatar(me.avatar)});
socket.on("chats_list",list=>{$("chats").innerHTML="";(list||[]).forEach(addChat)});
function addChat(c){const d=document.createElement("div");d.className="chat";d.dataset.id=c.id||c.username;const isDM=c.kind==="dm";d.innerHTML=`${avatarHtml(c,"small")}<div class="ct"><b>${esc(c.name||c.nickname||c.username)} ${c.verified?'<span class="verified">✓</span>':''}</b><small>${isDM?(c.online?'🟢 онлайн':'⚪ офлайн'):(c.kind==="channel"?'📢 Канал':'👥 Група')}</small></div>`;d.onclick=()=>isDM?openDM(c):openRoom(c);$("chats").appendChild(d)}
function scrollFeedToBottom(){const feed=$("feed");if(!feed)return;requestAnimationFrame(()=>{feed.scrollTop=feed.scrollHeight;});}
function shouldStickToBottom(){const feed=$("feed");if(!feed)return true;return feed.scrollHeight-feed.scrollTop-feed.clientHeight<90;}
function openRoom(c){$('headerActions').classList.add('hidden');current=c;currentKind="room";roomPerms=null;roomComments=[];$('sidebar').classList.add('mobile-hide');$('composer').classList.remove('hidden');$('headerAvatar').innerHTML=avatarHtml(c);$('headerInfo').innerHTML=`<b>${esc(c.name)} ${c.verified?'<span class="verified">✓</span>':''}</b><small>${esc(c.kind==="channel"?"Канал · "+(c.description||"Натисніть ⋮ для дій"):c.description||"Груповий чат")}</small>`;$('feed').innerHTML="";socket.emit("open_chat",{chatId:c.id});if(c.kind==="channel")socket.emit("channel_admin_data",{chatId:c.id})}
socket.on("chat_opened",x=>{setHeaderMode();current=x.chat;roomComments=x.comments||[];$('feed').innerHTML="";if(x.chat.banner)$('feed').insertAdjacentHTML("beforeend",`<div class="room-profile-head"><img class="room-banner" src="${x.chat.banner}" alt="Банер"><div class="room-avatar-overlay">${avatarHtml(x.chat)}</div></div>`);(x.messages||[]).forEach(renderRoomMessage);(x.polls||[]).forEach(renderPoll);scrollFeedToBottom()});
socket.on("channel_admin_data",x=>{if(current?.id!==x.chat.id)return;roomPerms=x.permissions||null;$("composer").classList.toggle("hidden",x.chat.kind==="channel"&&!roomPerms.can_publish);if(currentKind==="room")socket.emit("open_chat",{chatId:current.id})});

function fileHtml(m){if(!m.file_data)return"";if((m.file_type||"").startsWith("image/"))return`<div class="media-wrap"><img class="message-media" src="${m.file_data}" alt="Фото"></div>`;if((m.file_type||"").startsWith("video/"))return`<div class="media-wrap"><video class="message-media" src="${m.file_data}" controls></video></div>`;if((m.file_type||"").startsWith("audio/"))return`<div class="audio-wrap"><audio src="${m.file_data}" controls></audio></div>`;return`<a class="file-link" href="${m.file_data}" download="${esc(m.file_name||'file')}">📎 ${esc(m.file_name||'Файл')}</a>`}
function reactionsHtml(r){return Object.values(r||{}).map(x=>`<span class="reaction">${esc(x)}</span>`).join("")}
function commentsHtml(id){return `<div class="comments" data-comments="${id}">${roomComments.filter(c=>c.message_id===id).map(c=>`<div class="comment"><b>${esc(c.sender)}</b><span>${esc(c.text)}</span></div>`).join("")}</div>`}
function messageText(m){return m.text?`<div class="message-text">${esc(m.text).replace(/\n/g,"<br>")}</div>`:""}
function renderRoomMessage(m){const d=document.createElement("div");d.className="bubble"+(m.sender===me.username?" me":"");d.id="m_"+m.id;d.innerHTML=`<div class="message-author">${esc(m.nickname||m.sender)}</div>${fileHtml(m)}${messageText(m)}<div>${reactionsHtml(m.reactions)}</div><div class="meta">${new Date(m.created_at).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})} ${m.edited?'· ред.':''} ${m.pinned?'· 📌':''}</div>${commentsHtml(m.id)}<div class="actions"><button onclick="react('${m.id}','❤️')">❤️</button><button onclick="react('${m.id}','👍')">👍</button><button onclick="react('${m.id}','😂')">😂</button><button onclick="comment('${m.id}')">💬</button>${m.sender===me.username||roomPerms?.can_edit?`<button onclick="editMessage('${m.id}')">✏️</button>`:""}${m.sender===me.username||roomPerms?.can_delete?`<button onclick="deleteMessage('${m.id}')">🗑️</button>`:""}${roomPerms?.owner?`<button onclick="pin('${m.id}')">📌</button>`:""}</div>`;$('feed').appendChild(d)}
function renderDM(m){const d=document.createElement("div");d.className="bubble"+(m.sender===me.username?" me":"");d.id="m_"+m.id;d.innerHTML=`${fileHtml(m)}${messageText(m)}<div>${reactionsHtml(m.reactions)}</div><div class="meta">${new Date(m.created_at).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})} ${m.edited?'· ред.':''} ${m.pinned?'· 📌':''}</div><div class="actions">${m.sender===me.username?`<button onclick="editMessage('${m.id}')">✏️</button><button onclick="deleteMessage('${m.id}')">🗑️</button>`:""}<button onclick="react('${m.id}','❤️')">❤️</button><button onclick="react('${m.id}','👍')">👍</button><button onclick="pin('${m.id}')">📌</button></div>`;$('feed').appendChild(d)}

function send(){const text=$("msg").value.trim();if(!current||(!text&&!selectedFile))return;const d=currentKind==="dm"?{recipient:current.username,text,fileData:selectedFile?.data,fileName:selectedFile?.name,fileType:selectedFile?.type}:{chatId:current.id,text,fileData:selectedFile?.data,fileName:selectedFile?.name,fileType:selectedFile?.type};socket.emit(currentKind==="dm"?"send_direct_message":"send_chat_message",d);$("msg").value="";selectedFile=null;$("attach").value=""}
$("cameraBtn").onclick=()=>$("cameraInput").click();$("cameraInput").onchange=e=>{const f=e.target.files[0];if(f)fileToData(f,data=>selectedFile={data,name:f.name,type:f.type||'image/jpeg'});e.target.value=''};
$("send").onclick=send;$("msg").onkeydown=e=>{if(e.key==="Enter")send()};$("attachBtn").onclick=()=>$("attach").click();$("attach").onchange=e=>{const f=e.target.files[0];if(f)fileToData(f,data=>selectedFile={data,name:f.name,type:f.type})};
$("voice").onclick=async()=>{if(recording){recording.stop();return}try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});recordChunks=[];recording=new MediaRecorder(stream);recording.ondataavailable=e=>recordChunks.push(e.data);recording.onstop=()=>{const b=new Blob(recordChunks,{type:"audio/webm"});fileToData(b,data=>{if(current)socket.emit(currentKind==="dm"?"send_direct_message":"send_chat_message",currentKind==="dm"?{recipient:current.username,text:"🎙️ Голосове",fileData:data,fileName:"voice.webm",fileType:"audio/webm"}:{chatId:current.id,text:"🎙️ Голосове",fileData:data,fileName:"voice.webm",fileType:"audio/webm"});stream.getTracks().forEach(t=>t.stop());recording=null;$('voice').textContent="🎙️"})};recording.start();$('voice').textContent="⏹️"}catch(e){alert("Браузер не дозволив доступ до мікрофона.")}};

socket.on("chat_new_message",m=>{if(current?.id===m.chat_id){const stick=shouldStickToBottom();renderRoomMessage(m);if(stick)scrollFeedToBottom()}refresh()});
socket.on("direct_history",ms=>{currentKind="dm";setHeaderMode();$('feed').innerHTML="";(ms||[]).forEach(renderDM);scrollFeedToBottom()});
socket.on("new_direct_message",m=>{if(currentKind==="dm"&&current?.username&&(m.sender===current.username||m.recipient===current.username)){const stick=shouldStickToBottom();renderDM(m);if(stick)scrollFeedToBottom()}refresh()});
socket.on("message_updated",m=>{const e=$("m_"+m.id);if(!e)return;e.remove();if(m.chat_id)renderRoomMessage(m);else renderDM(m)});
window.react=(id,emoji)=>socket.emit("add_reaction",{id,emoji});window.editMessage=id=>{const t=prompt("Новий текст:");if(t!==null)socket.emit("edit_message",{id,newText:t})};window.deleteMessage=id=>{if(confirm("Видалити своє повідомлення?"))socket.emit("delete_message",{id})};window.pin=id=>socket.emit("pin_message",{id});window.comment=id=>{const t=prompt("Коментар до повідомлення:");if(t)socket.emit("add_comment",{messageId:id,text:t})};

function pollEl(p){const d=document.createElement("div");d.className="poll";d.dataset.poll=p.id;const votes=p.votes||{};const opts=Array.isArray(p.options)?p.options:JSON.parse(p.options||"[]");d.innerHTML=`<b>📊 ${esc(p.question)}</b>`+opts.map(o=>`<button onclick="vote('${p.id}',${JSON.stringify(o)})">${esc(o)} · ${Object.values(votes).filter(v=>v===o).length}</button>`).join("");return d}function renderPoll(p){$('feed').appendChild(pollEl(p))}
function renderComment(c){roomComments.push(c);const box=document.querySelector(`[data-comments="${c.message_id}"]`);if(box)box.insertAdjacentHTML('beforeend',`<div class="comment"><b>${esc(c.sender)}</b><span>${esc(c.text)}</span></div>`)}window.vote=(id,o)=>socket.emit("vote_poll",{pollId:id,option:o});socket.on("poll_created",x=>renderPoll(x.poll));socket.on("poll_updated",p=>document.querySelector(`[data-poll="${p.id}"]`)?.replaceWith(pollEl(p)));socket.on("comment_added",renderComment);

function search(){const q=$("search").value.trim();if(q)socket.emit("search_user",q)}$("searchBtn").onclick=search;$("search").onkeydown=e=>{if(e.key==="Enter")search()};
socket.on("user_found",u=>{$("searchResult").innerHTML=`<div class="result"><div class="result-row"><img src="${u.avatar||DEFAULT_AVATAR}"><div><b>${esc(u.nickname)}</b><small>${esc(u.username)} · ${u.online?'🟢 онлайн':'⚪ офлайн'}</small></div></div><small>${esc(u.description||'Опис відсутній')}</small></div>`;$('searchResult').onclick=()=>openDM(u)});
socket.on("chat_found",c=>{$("searchResult").innerHTML=`<div class="result"><div class="result-row"><img src="${c.avatar||DEFAULT_AVATAR}"><div><b>${esc(c.name)} ${c.verified?'<span class="verified">✓</span>':''}</b><small>${c.kind==='channel'?'📢 Канал':'👥 Група'}</small></div></div><small>${esc(c.description||'')}</small><div class="result-actions"><button onclick="joinFound('${c.id}')">Приєднатися</button><button onclick="previewFound('${c.id}')">Відкрити</button></div></div>`});
socket.on("user_not_found",()=>$("searchResult").innerHTML='<div class="result">Нічого не знайдено</div>');
function openDM(u){current=u;currentKind="dm";$('sidebar').classList.add('mobile-hide');$('composer').classList.remove('hidden');$('headerAvatar').innerHTML=`<img src="${u.avatar||DEFAULT_AVATAR}">`;$('headerInfo').innerHTML=`<b>${esc(u.nickname)} ${u.username===me.username?'(ви)':''}</b><small>${esc(u.username)} · ${u.online?'в мережі':'не в мережі'}</small>`;$('feed').innerHTML="";$('searchResult').innerHTML="";socket.emit("get_direct_messages",{username:u.username})}
function setHeaderMode(){const dm=currentKind==='dm';$('headerActions').classList.toggle('hidden',!dm)}
window.joinFound=id=>socket.emit("join_chat",{chatId:id});window.previewFound=id=>socket.emit("join_chat",{chatId:id});
socket.on("joined_chat",c=>{refresh();openRoom(c);$('searchResult').innerHTML=""});

$("profileBtn").onclick=()=>openProfile(me.username);$("profileBottom").onclick=()=>openProfile(me.username);$("menuBtn").onclick=()=>openProfile(me.username);$("back").onclick=()=>{$("sidebar").classList.remove("mobile-hide")};
function galleryPicker(title,inputId,onPick){return `<label class="form"><b>${title}</b><input id="${inputId}" type="file" accept="image/*"></label>`}
function openProfile(username){socket.emit("get_profile",{username})}
socket.on("profile_data",p=>{const own=p.username===me.username;const chans=(p.channels||[]).map(c=>`<div class="chat"><img src="${c.avatar||DEFAULT_AVATAR}"><div class="ct"><b>${esc(c.name)} ${c.verified?'<span class="verified">✓</span>':''}</b><small>Канал</small></div>${own?`<button class="icon-btn" onclick="removeProfileChannel('${c.id}')">×</button>`:""}</div>`).join("");let ownChannels=own?(p.ownedChannels||[]).map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join(""):"";$('modalContent').innerHTML=`<div class="form profile-card"><h2>${own?'Ваш профіль':'Профіль'}</h2><div class="profile-avatar-show">${avatarHtml(p,'big')}</div>${own?`<label class="gallery-avatar"><span>📷 Змінити аватар з галереї</span><input id="editAvatarFile" type="file" accept="image/*"></label>`:''}<input id="pn" value="${esc(p.nickname)}" ${own?'':'disabled'}><input id="pu" value="${esc(p.username)}" disabled><textarea id="pd" placeholder="Опис профілю" ${own?'':'disabled'}>${esc(p.description||'')}</textarea><div class="profile-items"><span class="pill">💎 ${p.crystals}</span>${p.frame?`<span class="pill">🖼️ ${esc(p.frame)}</span>`:''}${p.badge?`<span class="pill">${badgeEmoji(p.badge)} ${esc(p.badge)}</span>`:''}</div>${own?`<button onclick="saveProfile()">Зберегти профіль</button>`:''}<h3>📢 Канали в профілі</h3><div>${chans||'<span class="muted">Каналів ще немає</span>'}</div>${own&&ownChannels?`<select id="profileChannelSelect"><option value="">Додати свій канал...</option>${ownChannels}</select><button class="secondary" onclick="addProfileChannel()">Додати канал</button>`:''}<button class="secondary" onclick="openShop()">💎 Магазин</button>${own?'<button class="secondary" onclick="openOwnerPanel()">🛡️ Панель власника</button>':''}<button class="secondary" onclick="closeModal()">Закрити</button></div>`;if(own&&$("editAvatarFile"))$("editAvatarFile").onchange=e=>{const f=e.target.files[0];if(f)compressImage(f,x=>{me.avatar=x;localStorage.setItem('webchat_avatar',x)},700)};$('modal').classList.remove('hidden')});
window.saveProfile=()=>{const f=$("editAvatarFile")?.files?.[0];const done=avatar=>{socket.emit('update_profile',{newUsername:$('pu').value,nickname:$('pn').value,avatar:avatar||me.avatar,description:$('pd').value})};if(f)compressImage(f,done,700);else done(me.avatar)};socket.on('profile_updated',u=>{me=u;localStorage.setItem('webchat_username',u.username);localStorage.setItem('webchat_nickname',u.nickname);localStorage.setItem('webchat_avatar',u.avatar||DEFAULT_AVATAR);setAppAvatar(u.avatar);closeModal();refresh()});

window.addProfileChannel=()=>{const id=$("profileChannelSelect").value;if(id)socket.emit("profile_add_channel",{chatId:id})};window.removeProfileChannel=id=>socket.emit("profile_remove_channel",{chatId:id});socket.on("profile_channel_removed",()=>openProfile(me.username));

function mediaField(id,label,kind){return `<label class="form"><b>${label}</b><input id="${id}" type="file" accept="image/*"><small>Можна вибрати з галереї телефону</small></label>`}
window.openCreate=kind=>{$('modalContent').innerHTML=`<div class="form"><h2>${kind==='channel'?'📢 Створити канал':'👥 Створити груповий чат'}</h2><input id="cn" placeholder="Назва"><label class="gallery-avatar"><img id="createAvatarPreview" src="${DEFAULT_AVATAR}"><span>📷 Аватар з галереї</span><input id="createAvatarFile" type="file" accept="image/*"></label><textarea id="cd" placeholder="Опис (необов'язково)"></textarea><label class="form"><b>🖼️ Банер</b><input id="createBannerFile" type="file" accept="image/*"></label>${kind==='group'?'<input id="cm" placeholder="Учасники: @user1, @user2">':''}<button onclick="createNow('${kind}')">Створити</button><button class="secondary" onclick="closeModal()">Скасувати</button></div>`;$('modal').classList.remove('hidden');$('createAvatarFile').onchange=e=>{const f=e.target.files[0];if(f)compressImage(f,x=>$('createAvatarPreview').src=x,700)}};
window.createNow=kind=>{const done=(avatar,banner)=>{const d={name:$('cn').value,avatar:avatar||DEFAULT_AVATAR,description:$('cd').value,banner:banner||null};if(kind==='group')d.members=$('cm').value.split(',').map(x=>x.trim()).filter(Boolean);socket.emit(kind==='channel'?'create_channel':'create_chat',d)};const af=$('createAvatarFile').files[0],bf=$('createBannerFile').files[0];const nextA=cb=>af?compressImage(af,cb,700):cb(DEFAULT_AVATAR);nextA(a=>{if(bf)compressImage(bf,b=>done(a,b),1100);else done(a,null)})};
socket.on("chat_created",c=>{closeModal();refresh();openRoom(c)});

function openShop(){socket.emit("shop_catalog");$('modalContent').innerHTML=`<div class="form"><h2>💎 Магазин</h2><div class="pill">Баланс: ${me?.crystals||0} 💎</div><div id="shop" class="shop-grid"></div><hr><button onclick="createPromo()">🎟️ Створити промокод</button><input id="redeemCode" placeholder="Введіть промокод"><button onclick="socket.emit('redeem_promo',{code:$('redeemCode').value})">Активувати промокод</button><button class="secondary" onclick="closeModal()">Закрити</button></div>`;$('modal').classList.remove('hidden')}
window.openShop=openShop;$("shopBtn").onclick=openShop;
socket.on("shop_catalog",x=>{const e=$('shop');if(!e)return;e.innerHTML="";const owned=new Set((x.owned||[]).map(i=>i.item_type+":"+i.item_id));(x.frames||[]).forEach(i=>{const id=i[0],own=owned.has('frame:'+id),eq=x.equipped?.frame===id;e.insertAdjacentHTML('beforeend',`<div class="shopitem"><div class="frame-preview" style="background:${i[2]}"></div><b>${esc(i[1])}</b><p>💎 ${i[3]}</p>${own?(eq?'<button class="equipped" disabled>✓ Одягнено</button>':`<button onclick="equip('frame','${id}')">Одягнути</button>`):`<button onclick="buy('frame','${id}')">Купити</button>`}</div>`)});(x.badges||[]).forEach(i=>{const id=i[0],own=owned.has('badge:'+id),eq=x.equipped?.badge===id;e.insertAdjacentHTML('beforeend',`<div class="shopitem"><div style="font-size:42px">${i[1]}</div><b>${esc(i[2])}</b><p>💎 ${i[3]}</p>${own?(eq?'<button class="equipped" disabled>✓ Одягнено</button>':`<button onclick="equip('badge','${id}')">Одягнути</button>`):`<button onclick="buy('badge','${id}')">Купити</button>`}</div>`)});});window.buy=(type,id)=>socket.emit("buy_item",{type,id});window.equip=(type,id)=>socket.emit("equip_item",{type,id});socket.on('equipped',()=>{socket.emit('get_profile',{username:me.username});socket.emit('shop_catalog');socket.emit('get_balance')});

window.createPromo=()=>{$('modalContent').innerHTML=`<div class="form"><h2>🎟️ Створити промокод</h2><input id="pc" placeholder="Код"><input id="pr" type="number" min="1" placeholder="Кристалів за активацію"><input id="pa" type="number" min="1" placeholder="Кількість активацій"><p class="muted">З балансу спишеться: нагорода × активації.</p><button onclick="socket.emit('create_promo',{code:$('pc').value,reward:+$('pr').value,activations:+$('pa').value})">Створити</button><button class="secondary" onclick="openShop()">Назад</button></div>`};

$("headerMore").onclick=()=>{if(!current)return;if(currentKind==='dm')return openDMMenu();const owner=current.owner===me.username;const canEdit=owner||roomPerms?.can_edit_channel;const canPublish=owner||roomPerms?.can_publish;$('modalContent').innerHTML=`<div class="form"><h2>${esc(current.name)} ${current.verified?'<span class="verified">✓</span>':''}</h2><button onclick="openSubscribers()">👥 Підписники</button>${current.kind==='channel'&&(owner||roomPerms?.can_edit_channel||roomPerms?.can_kick)?'<button onclick="openSubscribers()">🛡️ Адмін-панель</button>':''}${current.kind==='channel'&&canEdit?'<button onclick="editRoom()">✏️ Редагувати канал</button>':''}${current.kind==='channel'&&canPublish?'<button onclick="createPoll()">📊 Створити опитування</button>':''}${current.kind==='channel'&&canPublish?'<button onclick="startLive()">📺 Почати трансляцію</button>':''}<button onclick="leaveRoom()">🚪 Покинути</button>${owner?'<button class="danger" onclick="deleteRoom()">🗑️ Видалити</button>':''}<button class="secondary" onclick="closeModal()">Закрити</button></div>`;$('modal').classList.remove('hidden')};
function openDMMenu(){$('modalContent').innerHTML=`<div class="form"><h2>${esc(current.nickname||current.username)}</h2><button onclick="openProfile('${esc(current.username)}')">👤 Переглянути профіль</button><button onclick="blockUser()">🚫 Заблокувати</button><button class="danger" onclick="deleteDirectChat()">🗑️ Видалити чат</button><button class="secondary" onclick="closeModal()">Закрити</button></div>`;$('modal').classList.remove('hidden')}
window.blockUser=()=>{if(confirm("Заблокувати користувача?"))socket.emit("block_user",{username:current.username})};window.deleteDirectChat=()=>{if(confirm("Видалити всю історію цього чату?"))socket.emit("delete_direct_chat",{username:current.username})};socket.on("direct_chat_deleted",()=>{closeModal();$('feed').innerHTML='<div class="empty-state"><div>💬</div><b>Чат видалено</b></div>';refresh()});socket.on("user_blocked",()=>{closeModal();alert("Користувача заблоковано.")});
window.openSubscribers=()=>{if(!current||current.kind!=='channel')return;socket.emit('channel_admin_data',{chatId:current.id});socket.once('channel_admin_data',renderSubscribers)};
function renderSubscribers(x){const owner=x.chat.owner===me.username;const canKick=x.permissions?.can_kick;const list=(x.members||[]).map(m=>{const admin=m.role==='admin';return `<div class="subscriber"><div>${avatarHtml(m,'small')}</div><div class="subscriber-main"><b>${esc(m.nickname)} ${admin?'<span class="admin-tag">АДМІН</span>':''}</b><small>${esc(m.username)}</small></div>${owner&&m.username!==x.chat.owner?`<button onclick="adminEdit('${m.username.replace(/'/g,"\'")}')">${admin?'⚙️':'👑'}</button>`:''}${canKick&&m.username!==me.username&&m.username!==x.chat.owner?`<button class="danger-mini" onclick="kickMember('${m.username.replace(/'/g,"\'")}')">×</button>`:''}</div>`}).join('');$('modalContent').innerHTML=`<div class="form"><h2>👥 Підписники · ${(x.members||[]).length}</h2><div class="subscribers">${list||'<span class="muted">Немає підписників</span>'}</div><button class="secondary" onclick="closeModal()">Закрити</button></div>`;$('modal').classList.remove('hidden')}
window.adminEdit=username=>{const x={chatId:current.id,username};socket.emit('channel_admin_data',{chatId:current.id});socket.once('channel_admin_data',data=>{const m=data.members.find(v=>v.username===username)||{};const p={can_delete:!!m.can_delete,can_edit:!!m.can_edit,can_edit_channel:!!m.can_edit_channel,can_publish:!!m.can_publish,can_kick:!!m.can_kick};$('modalContent').innerHTML=`<div class="form"><h2>🛡️ Права ${esc(username)}</h2>${[['can_delete','Видаляти чужі повідомлення'],['can_edit','Редагувати чужі повідомлення'],['can_edit_channel','Редагувати канал'],['can_publish','Публікувати повідомлення'],['can_kick','Видаляти підписників']].map(([k,t])=>`<label class="check-row"><input id="perm_${k}" type="checkbox" ${p[k]?'checked':''}> ${t}</label>`).join('')}<button onclick="saveAdmin('${username.replace(/'/g,"\'")}')">Зберегти права</button><button class="danger" onclick="socket.emit('remove_channel_admin',{chatId:current.id,username:'${username.replace(/'/g,"\'")}'});openSubscribers()">Зняти адмінку</button><button class="secondary" onclick="openSubscribers()">Назад</button></div>`;$('modal').classList.remove('hidden')})};
window.saveAdmin=username=>{const permissions={can_delete:$('perm_can_delete').checked,can_edit:$('perm_can_edit').checked,can_edit_channel:$('perm_can_edit_channel').checked,can_publish:$('perm_can_publish').checked,can_kick:$('perm_can_kick').checked};socket.emit('set_channel_admin',{chatId:current.id,username,permissions});openSubscribers()};window.kickMember=username=>{if(confirm('Видалити підписника з каналу?'))socket.emit('kick_channel_member',{chatId:current.id,username})};socket.on('channel_admin_changed',()=>{if(current?.kind==='channel')socket.emit('channel_admin_data',{chatId:current.id})});

window.editRoom=()=>{$('modalContent').innerHTML=`<div class="form"><h2>✏️ Редагувати ${current.kind==='channel'?'канал':'чат'}</h2><input id="en" value="${esc(current.name)}"><label class="gallery-avatar"><img id="editRoomAvatarPreview" src="${current.avatar||DEFAULT_AVATAR}"><span>📷 Змінити аватар</span><input id="editRoomAvatarFile" type="file" accept="image/*"></label><textarea id="ed">${esc(current.description||'')}</textarea><label class="form"><b>🖼️ Змінити банер</b><input id="editRoomBannerFile" type="file" accept="image/*"></label><button onclick="saveRoomEdit()">Зберегти</button><button class="secondary" onclick="closeModal()">Скасувати</button></div>`;$('editRoomAvatarFile').onchange=e=>{const f=e.target.files[0];if(f)compressImage(f,x=>$('editRoomAvatarPreview').src=x,700)}};
window.saveRoomEdit=()=>{const af=$('editRoomAvatarFile').files[0],bf=$('editRoomBannerFile').files[0];const done=(a,b)=>socket.emit('edit_chat',{chatId:current.id,name:$('en').value,avatar:a,description:$('ed').value,banner:b});const na=cb=>af?compressImage(af,cb,700):cb(current.avatar||DEFAULT_AVATAR);na(a=>{if(bf)compressImage(bf,b=>done(a,b),1100);else done(a,current.banner||null)})};window.leaveRoom=()=>socket.emit('leave_chat',{chatId:current.id});window.deleteRoom=()=>{if(confirm('Видалити цей чат/канал?'))socket.emit('delete_chat',{chatId:current.id})};
socket.on("chat_deleted",id=>{if(current?.id===id){current=null;$('feed').innerHTML='<div class="empty-state"><div>🗑️</div><b>Видалено</b></div>';$('composer').classList.add('hidden')}refresh();closeModal()});socket.on("left_chat",()=>{current=null;$('feed').innerHTML='<div class="empty-state"><div>🚪</div><b>Ви покинули чат</b></div>';$('composer').classList.add('hidden');refresh();closeModal()});socket.on("chat_updated",c=>{current=c;closeModal();openRoom(c);refresh()});

function createPoll(){$('modalContent').innerHTML=`<div class="form"><h2>📊 Опитування</h2><input id="pollQ" placeholder="Питання"><input class="pollOpt" placeholder="Варіант 1"><input class="pollOpt" placeholder="Варіант 2"><input class="pollOpt" placeholder="Варіант 3"><button onclick="sendPoll()">Опублікувати</button><button class="secondary" onclick="closeModal()">Скасувати</button></div>`}window.createPoll=createPoll;window.sendPoll=()=>{const options=[...document.querySelectorAll('.pollOpt')].map(x=>x.value.trim()).filter(Boolean);if(options.length<2)return alert('Потрібно мінімум 2 варіанти.');socket.emit('create_poll',{chatId:current.id,question:$('pollQ').value,options});closeModal()};

function openOwnerPanel(){ownerPass="";$('modalContent').innerHTML=`<div class="form"><h2>🛡️ Панель власника WebChat</h2><input id="ownerPassword" type="password" placeholder="Пароль власника"><button onclick="ownerLogin()">Увійти</button><div id="ownerTools"></div><button class="secondary" onclick="closeModal()">Закрити</button></div>`;$('modal').classList.remove('hidden')}
window.openOwnerPanel=openOwnerPanel;$("ownerBtn").onclick=openOwnerPanel;$("ownerOpenAuth").onclick=openOwnerPanel;
window.ownerLogin=()=>{ownerPass=$("ownerPassword").value;socket.emit('owner_login',{password:ownerPass})};socket.on('owner_auth',x=>{if(!x.ok)return alert('Невірний пароль');ownerAuth=true;socket.emit('owner_list_channels',{password:ownerPass});$("ownerTools").innerHTML=`<div class="owner-grid"><input id="ownerUser" placeholder="@користувач"><button onclick="socket.emit('owner_balance',{password:ownerPass,username:$('ownerUser').value})">💎 ∞ Кристалів</button><input id="ownerChannelId" placeholder="ID каналу"><button onclick="verifyOwner(true)">✓ Галочка</button><button onclick="verifyOwner(false)">Зняти галочку</button><button class="danger" onclick="deleteOwnerChannel()">🗑️ Видалити канал</button></div><hr><h3>Канали</h3><div id="ownerChannels">Завантаження...</div>`});
function verifyOwner(v){socket.emit('owner_verify_channel',{password:ownerPass,chatId:$('ownerChannelId').value,verified:v})}function deleteOwnerChannel(){if(confirm('Видалити канал назавжди?'))socket.emit('owner_delete_channel',{password:ownerPass,chatId:$('ownerChannelId').value})}
socket.on('owner_channels',list=>{const e=$('ownerChannels');if(!e)return;e.innerHTML=(list||[]).map(c=>`<div class="chat"><img src="${c.avatar||DEFAULT_AVATAR}"><div class="ct"><b>${esc(c.name)} ${c.verified?'<span class="verified">✓</span>':''}</b><small>ID: ${esc(c.id)} · власник ${esc(c.owner)}</small></div><button class="icon-btn" onclick="$('ownerChannelId').value='${c.id}'">↗</button></div>`).join('')||'<span class="muted">Каналів немає</span>'});socket.on('owner_balance_result',x=>alert(`${x.username}: ∞ кристалів`));socket.on('chat_changed',()=>{if(ownerAuth)socket.emit('owner_list_channels',{password:ownerPass});refresh()});

$("modal").onclick=e=>{if(e.target.id==="modal")closeModal()};
socket.on("connect",()=>{const u=localStorage.getItem('webchat_username');if(u)socket.emit('register',{username:u,nickname:localStorage.getItem('webchat_nickname')||'Користувач',avatar:localStorage.getItem('webchat_avatar')||DEFAULT_AVATAR})});
socket.on("disconnect",()=>console.log('WebChat: з’єднання втрачено'));
function badgeEmoji(id){return ({crystals:'💎',webchat:'💬',donater:'💰',creator:'✨',verified:'✓',star:'⭐',crown:'👑'})[id]||''}


async function createCallPeer(){
  callPC=new RTCPeerConnection({iceServers:[{urls:'stun:stun.l.google.com:19302'}]});
  callStream?.getTracks().forEach(t=>callPC.addTrack(t,callStream));
  callPC.ontrack=e=>{if(e.streams[0])$('remoteVideo').srcObject=e.streams[0]};
  callPC.onicecandidate=e=>{if(e.candidate&&callPeer)socket.emit('call_ice',{to:callPeer,candidate:e.candidate})};
  callPC.onconnectionstatechange=()=>{const st=callPC?.connectionState;if(st==='connected')$('callStatus').textContent='Дзвінок триває';if(st==='failed')$('callStatus').textContent='Не вдалося встановити з’єднання'};
}
async function flushCallIce(){if(!callPC)return;for(const c of callIceQueue.splice(0)){try{await callPC.addIceCandidate(c)}catch(e){}}}
async function startCall(type){
  if(currentKind!=='dm'||!current?.username)return;
  if(!navigator.mediaDevices?.getUserMedia)return alert('Цей браузер не підтримує камеру/мікрофон.');
  await endCall(false); callIceQueue=[]; callType=type;callPeer=current.username;callMuted=false;callCamera=type==='video';
  try{
    callStream=await navigator.mediaDevices.getUserMedia({audio:true,video:type==='video'});
    showCallUI(`${type==='video'?'📹':'📞'} ${current.nickname||current.username}`);
    $('localVideo').srcObject=callStream;$('localVideo').classList.toggle('hidden',type!=='video');
    await createCallPeer();
    const offer=await callPC.createOffer();await callPC.setLocalDescription(offer);
    socket.emit('call_offer',{to:callPeer,offer:callPC.localDescription,type,callId:socket.id});
    $('callStatus').textContent='Виклик надсилається…';
  }catch(e){alert('Не вдалося отримати доступ до камери або мікрофона.');await endCall(false)}
}
function showCallUI(title){$('callTitle').textContent=title;$('callStatus').textContent='Підключення…';$('callLayer').classList.remove('hidden')}
async function endCall(notify=true){if(notify&&callPeer)socket.emit('call_end',{to:callPeer});if(callPC){callPC.ontrack=null;callPC.onicecandidate=null;callPC.close();callPC=null}if(callStream){callStream.getTracks().forEach(t=>t.stop());callStream=null}$('remoteVideo').srcObject=null;$('localVideo').srcObject=null;$('callLayer').classList.add('hidden');callPeer=null;callType=null;callIceQueue=[]}
$('audioCall').onclick=()=>startCall('audio');$('videoCall').onclick=()=>startCall('video');$('endCall').onclick=()=>endCall(true);
$('muteCall').onclick=()=>{callMuted=!callMuted;callStream?.getAudioTracks().forEach(t=>t.enabled=!callMuted);$('muteCall').textContent=callMuted?'🔇':'🎙️'};
$('cameraCall').onclick=()=>{if(callType!=='video')return;callCamera=!callCamera;callStream?.getVideoTracks().forEach(t=>t.enabled=callCamera);$('cameraCall').textContent=callCamera?'📷':'🚫'};
socket.on('incoming_call',async d=>{
  if(callPC)return;
  const ok=confirm(`${d.type==='video'?'📹':'📞'} ${d.from} телефонує. Прийняти?`);
  if(!ok){socket.emit('call_end',{to:d.from});return}
  callPeer=d.from;callType=d.type||'audio';callIceQueue=[];
  try{
    callStream=await navigator.mediaDevices.getUserMedia({audio:true,video:callType==='video'});
    showCallUI(`${callType==='video'?'📹':'📞'} ${d.from}`);$('localVideo').srcObject=callStream;$('localVideo').classList.toggle('hidden',callType!=='video');
    await createCallPeer();
    await callPC.setRemoteDescription(d.offer);await flushCallIce();
    const ans=await callPC.createAnswer();await callPC.setLocalDescription(ans);
    socket.emit('call_answer',{to:callPeer,answer:callPC.localDescription});$('callStatus').textContent='Дзвінок триває';
  }catch(e){$('callStatus').textContent='Не вдалося прийняти дзвінок';await endCall(true)}
});
socket.on('call_answer',async d=>{if(!callPC)return;try{await callPC.setRemoteDescription(d.answer);await flushCallIce();$('callStatus').textContent='Дзвінок триває'}catch(e){$('callStatus').textContent='Помилка з’єднання'}});
socket.on('call_ice',async d=>{if(!d.candidate)return;if(callPC?.remoteDescription?.type){try{await callPC.addIceCandidate(d.candidate)}catch(e){}}else callIceQueue.push(d.candidate)});
socket.on('call_ended',()=>endCall(false));
socket.on('call_unavailable',d=>{if(callPeer===d.to||callPeer===d.username){$('callStatus').textContent='Користувач зараз не в мережі';setTimeout(()=>endCall(false),1800)}});
socket.on('call_delivered',()=>{if(callPeer) $('callStatus').textContent='Виклик доставлено…'});

async function startLive(){
 if(currentKind!=='room'||current?.kind!=='channel'||!(current.owner===me.username||roomPerms?.can_publish))return alert('Немає дозволу на трансляцію.');
 try{liveStream=await navigator.mediaDevices.getUserMedia({video:true,audio:true});liveHost=true;liveChatId=current.id;$('liveTitle').textContent='🔴 '+current.name;$('liveVideo').srcObject=liveStream;$('liveVideo').muted=true;$('liveStatus').textContent='Ви ведете трансляцію';$('stopLive').textContent='Завершити';$('liveLayer').classList.remove('hidden');socket.emit('live_start',{chatId:current.id});}catch(e){alert('Не вдалося отримати доступ до камери або мікрофона.')}}
async function stopLive(){if(!liveChatId)return;socket.emit('live_stop',{chatId:liveChatId});livePeers.forEach(pc=>pc.close());livePeers.clear();liveStream?.getTracks().forEach(t=>t.stop());liveStream=null;liveHost=false;liveChatId=null;$('liveVideo').srcObject=null;$('liveLayer').classList.add('hidden')}
$('stopLive').onclick=stopLive;
socket.on('live_started',d=>{if(d.chatId===current?.id){$('headerInfo').innerHTML+=` <span class="live-badge">🔴 LIVE</span>`;if(d.host!==me.username){if(confirm('У каналі розпочалася трансляція. Переглянути?'))joinLive(d.chatId)}}});
async function joinLive(chatId){liveChatId=chatId;liveHost=false;$('liveTitle').textContent='📺 Трансляція';$('liveStatus').textContent='Підключення…';$('liveLayer').classList.remove('hidden');socket.emit('live_join',{chatId})}
socket.on('live_offer',async d=>{try{livePC=new RTCPeerConnection({iceServers:[{urls:'stun:stun.l.google.com:19302'}]});livePC.ontrack=e=>$('liveVideo').srcObject=e.streams[0];livePC.onicecandidate=e=>e.candidate&&socket.emit('live_ice',{to:d.fromSocket,candidate:e.candidate});await livePC.setRemoteDescription(d.offer);const ans=await livePC.createAnswer();await livePC.setLocalDescription(ans);socket.emit('live_answer',{to:d.fromSocket,answer:ans});$('liveStatus').textContent='Трансляція триває';}catch(e){$('liveStatus').textContent='Не вдалося підключитися'}});
socket.on('live_answer',async d=>{const pc=livePeers.get(d.viewerSocket);if(pc)await pc.setRemoteDescription(d.answer)});
socket.on('live_ice',async d=>{try{if(liveHost){const pc=livePeers.get(d.fromSocket);if(pc&&d.candidate)await pc.addIceCandidate(d.candidate)}else if(livePC&&d.candidate)await livePC.addIceCandidate(d.candidate)}catch(e){}});
socket.on('live_viewer_join',async d=>{if(!liveHost||!liveStream)return;const pc=new RTCPeerConnection({iceServers:[{urls:'stun:stun.l.google.com:19302'}]});livePeers.set(d.viewerSocket,pc);liveStream.getTracks().forEach(t=>pc.addTrack(t,liveStream));pc.onicecandidate=e=>e.candidate&&socket.emit('live_ice',{to:d.viewerSocket,candidate:e.candidate});const offer=await pc.createOffer();await pc.setLocalDescription(offer);socket.emit('live_offer',{to:d.viewerSocket,offer,fromSocket:socket.id})});
socket.on('live_stopped',d=>{if(liveChatId===d.chatId&&!liveHost){livePC?.close();livePC=null;$('liveLayer').classList.add('hidden');liveChatId=null;$('liveVideo').srcObject=null;$('liveStatus').textContent='Трансляцію завершено'}});

